name: ZenDo
description: "A beautiful and smart task management app to organize your daily life."

publish_to: 'none' 


version: 1.1.0+2

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  flutter_colorpicker: ^1.1.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_timezone: ^4.1.1
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  win_toast: ^0.4.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/adnan.png
    - assets/icons/icon.png

  uses-material-design: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  adaptive_icon_background: "#00BCD4"